# fly.toml app configuration file generated for upeapp on 2023-09-07T18:01:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "upeapp"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
